### PR TITLE
code-of-conduct

### PR DESCRIPTION
**Pull request by shivansh12032004**
Code of Conduct was added

### CODE REVIEW

**Comment by shivansh12032004** [comment]
Please also assign the tag of hacktoberfest-accepted. Thanks

**Comment by vibgyor786** [comment]
Thanks for the contribution @shivansh12032004

**Comment by shivansh12032004** [comment]
@vibgyor786 can you add hacktoberfest-accepted under this pr? As I've done this under hacktoberfest. thanks

**Comment by vibgyor786** [comment]
> @vibgyor786 can you add hacktoberfest-accepted under this pr? As I've done this under hacktoberfest. thanks

yeah i added that label to that issue , and also added it in your pr request comments.

**Pull request merged**
