### PR TITLE
Created new UI Card similar to an atm card.In case any modifications required I'm always ready for support

### PR DESCRIPTION
**Pull request by SukarayamJanjua**
Here is a screenshot of what it looks like...minute changes can be done acc. to personal use

https://user-images.githubusercontent.com/94704551/193467941-716d6a64-a546-414d-b9aa-d1ad90d95523.png

### CODE REVIEW

**Comment by vibgyor786** [comment]
@SukarayamJanjua can you add some more details in the right side of the card as shown in the image .
ui card

**Comment by SukarayamJanjua** [comment]
Hey!! I've added some details you can have a look 

https://user-images.githubusercontent.com/94704551/193557710-2d27c51a-62b5-4393-9ca7-4170549a045e.png

**Comment by SukarayamJanjua** [comment]
@vibgyor786 kindly look through it...waiting for your response!!🙂

**Comment by vibgyor786** [comment]
> @vibgyor786 kindly look through it...waiting for your response!!🙂

it looks good but it will be good if you can make it little better :)

**Comment by vibgyor786** [comment]
> @vibgyor786 kindly look through it...waiting for your response!!🙂

it looks good but it will be good if you can make it little better :)

**Comment by SukarayamJanjua** [comment]
@vibgyor786 Is it better now?...actually I'm not getting it exactly what kind of card u want so thats why its quite tough to interpret and make what you are probably thinking...well here it is from my side...🙂

https://user-images.githubusercontent.com/94704551/193639324-67833003-3be9-4f27-a38c-bb9669111789.png

**Comment by vibgyor786** [comment]
> @vibgyor786 Is it better now?...actually I'm not getting it exactly what kind of card u want so thats why its quite tough to interpret and make what you are probably thinking...well here it is from my side...🙂
> 
> https://user-images.githubusercontent.com/94704551/193639324-67833003-3be9-4f27-a38c-bb9669111789.pn
add your name in readme contributor section then i will accept the pr

**Comment by SukarayamJanjua** [comment]
Done adding my name in contributors !!...Thankyou @vibgyor786 It was a great experience working with you sir !!

**Comment by vibgyor786** [comment]
@SukarayamJanjua Thanks for the contribution , i am merrging your pr :)

**Pull request merged**
