### PR TITLE
Horizontal progress bar with loading percentage

### PR DESCRIPTION
**Pull request by Akshay9607**
As state concept is not there in html , so changing percentage value with progress bar is not possible , therefore for changing percentage value , in console we have to call a function updateProgressBar(progressBar , percentage value) .

if there is any other way of doing this , Please let me know .

### CODE REVIEW

**Comment by Akshay9607** [comment]
As state concept is not there in html , so changing percentage value with progress bar is not possible , therefore for changing percentage value , in console we have to call a function updateProgressBar(progressBar , percentage value) .

result image : 
loading

if there is any other way of doing this , Please let me know .

**Comment by Akshay9607** [comment]
Hey , i made the changes mentioned above , can you please review it and merge the pull request , if any further changes to be made let me know.

**Comment by vibgyor786** [comment]
@Akshay9607 add your name in contributor section in readme.md then i will merge your pull request .

**Comment by Akshay9607** [comment]
> @Akshay9607 add your name in contributor section in readme.md then i will merge your pull request .

yeah sure !!!

**Comment by Akshay9607** [comment]
Hey , i added my name in README.md , can you review it once please and merge my Pull Request

**Comment by vibgyor786** [comment]
@Akshay9607 i am merging your pull request

**Pull request merged**
